sudo: false
addons:
  postgresql: "9.3"
  apt:
    packages:
    - libxslt1-dev
    - libxml2-dev
before_install:
- cd $TRAVIS_BUILD_DIR/src/$COMPONENT && bundle config build.nokogiri --use-system-libraries
before_script:
- cd $TRAVIS_BUILD_DIR/src/$COMPONENT && bundle exec rake $COMPONENT:travis:before_script
branches:
  only:
  - master
bundler_args: "--without development --jobs 7"
cache:
  apt: true
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/src/$COMPONENT/vendor/bundle
env:
  global:
  - CAPYBARA_SCREENSHOT_TO_S3=true
  - secure: rzoy57s+oxvw27HStU1VNHN7fS525ocQo11bmASbwG5Ax6I4X/dwWofQCoZPoGrXisMw5RQaa7e3bHJpATZsMJC67Sf6gbfSOIYY7tISXuCFh9q/19YPGltdwZkP3OgawEpufA8zcMHzD5nvWNXq4c4TKRdtX6mHQVIAOJ9u6qY=
  - secure: zmBguz2BE0upyqhYJbr73wXVPkLO8Me1WisL4bh6B+HVAK6fCHSkdf/FGiiGz1h+HLF39K8DweNw7uPoyQfDxpN3E14MCUkk+jG7I+0IyT5istEsLeJXEBDp2sqgBYcPpCvw73Q4SGYsG2Uf+Ofz5ihKTw4zaxYGYkbuJ7UAs80=
  - secure: RfOhiaSlkbK0x798woj4sASE0VM2gGn6tdUqkWLWeOYvlRT1wqWs8ZLrVALfpyDiutFyxSPFIALp1fObCBTzswOtBxAQXc347dqVbYmqH92VbTp+qSJO9+dOHIoGe9hrV89Fe73AeL85n2rXzPEXLSJoE3Ap4F8nAGbkpbSf/+M=
  matrix:
  - COMPONENT=supermarket
  - COMPONENT=fieri
language: ruby
notifications:
  email: false
  slack:
    secure: YhfiTSk7726AGK9H8761vEbu7wgKzh8zZll/PJuH2dmUy5myrV2nOxf7h6cbsEZcVA+dJ6jpGuLJnsoCBrneh2p7MKf+3wlwxZKE/sns0doMjf5L0i58guGEIVUbE6ydCoC+z65oniq5r/keS5kOs1Rate8wK2DvzgKN7Sjmx58=
rvm:
- 2.3.0
script:
- cd $TRAVIS_BUILD_DIR/src/$COMPONENT && bundle exec rake $COMPONENT:travis:script
services:
  - redis-server
  - postgresql
